apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-service
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    name: wordpress-rook